### PR TITLE
Update to ZeeQs 2.0.0

### PR DESCRIPTION
**Pull request by falko**
Depends on https://github.com/camunda-community-hub/zeeqs/issues/153

### CODE REVIEW

**Comment by ChrisKujawa** [comment]
Hey @falko sorry but I will not review it, we decided to abandon this helm chart. Feel free to raise it on the stakeholder round or take it over.

**Comment by falko** [comment]
So then it will also be removed from [zeebe-full-helm](https://github.com/camunda-community-hub/zeebe-full-helm)?

**Comment by falko** [comment]
Is the plan to just not update it anymore or do you want to remove it completely from the chart repository. I just spend some good time figuring out how to update it because its docker repo changed and Hazelcase needed updating, too. Would kind of hurt to throw that away.

**Comment by ChrisKujawa** [comment]
We marked it as seeking for maintainer. The plan was not to update, since I felt not comfortable to maintain this project and the other charts are enough from my side. In respect of work but also was not sure whether this chart is really in use. We have no metrics unfortunately.

**Comment by falko** [comment]
I could be interims maintainer while we still look for a new maintainer ;-)

@celanthe: Where do I sign?

**Comment by ChrisKujawa** [comment]
@falko I added you as owner https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS 

I think the rest can be done by @celanthe (like updating the badge etc.)

**Comment by celanthe** [comment]
@falko @Zelldon I updated the badges in the README, so that's all set! :) Thank you so much for stepping up as an interim maintainer for these charts, Falko! :D 

In light of that, would you like me to merge this PR?

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602282 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602282 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602282 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602282 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ChrisKujawa** [comment]
Thanks @celanthe 

All fine I can do that :)

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602684 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ChrisKujawa** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7#issuecomment-898602684 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=camunda-community-hub%2Fzeebe-zeeqs-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/camunda-community-hub/zeebe-zeeqs-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
